name: Pull Request Validation

on:
  pull_request:
    branches: [ master ]
  push:
    branches: 
    - master
    - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        arguments: build
    - name: JUnit Report Action
      if: always()
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: 'build/test-results/test/TEST-*.xml'
    - name: Codecov
      uses: codecov/codecov-action@v1.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN}}
        directory: build/reports/jacoco/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Build-Archive
        path: build
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kotlin Linter Check
        uses: vroy/gha-kotlin-linter@v2
